version: 2
updates:
    # Enable version updates for npm
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      open-pull-requests-limit: 2

    # Enable version updates for github actions
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
